version: '3'

services: 
  db:
    image: postgres:15.3-alpine
    restart: always
    ports: 
      - "${DB_PORT}:5432"
    environment: 
      POSTGRES_PASSWORD: ${DB_PSW}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes: 
      - ./database:/var/lib/postgresql